#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InsideInning.Droid.Resource", IsApplication=true)]

namespace InsideInning.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Balance128 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blog = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Calendar128 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Employee128 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int facebook = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int googleplus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int index = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int instagram = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int NotePad = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NotePad128 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Notify128 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int refresh = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int scott = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int slideout = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int twitter = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int twitternav = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
