#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InsideInning.Droid.Resource", IsApplication=true)]

namespace InsideInning.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::InsideInning.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::InsideInning.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::InsideInning.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::InsideInning.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::InsideInning.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::InsideInning.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::InsideInning.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::InsideInning.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::InsideInning.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::InsideInning.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::InsideInning.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::InsideInning.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::InsideInning.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::InsideInning.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::InsideInning.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::InsideInning.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::InsideInning.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::InsideInning.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::InsideInning.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::InsideInning.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::InsideInning.Droid.Resource.Id.calendar_view;
			//global::XLabs.Forms.Resource.Id.left_arrow = global::InsideInning.Droid.Resource.Id.left_arrow;
			//global::XLabs.Forms.Resource.Id.right_arrow = global::InsideInning.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::InsideInning.Droid.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::InsideInning.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::InsideInning.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::InsideInning.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::InsideInning.Droid.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::InsideInning.Droid.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::InsideInning.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::InsideInning.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::InsideInning.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::InsideInning.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::InsideInning.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::InsideInning.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::InsideInning.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::InsideInning.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::InsideInning.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::InsideInning.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::InsideInning.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::InsideInning.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::InsideInning.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int state_current_month = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int state_highlighted = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int state_range_first = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int state_range_last = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int state_range_middle = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int state_selectable = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int state_today = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int calendar_text_selector = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ad16 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int balance = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Balance128 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Birthday = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blog = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int blur = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Calendar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Calendar128 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int calendar_bg_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cover = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Coverpage = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int email = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Employee128 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int facebook = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int FromDate = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Gender = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleplus = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int holiday = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_launcher = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int iiFemaleSelectionButton = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int iiListBack = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int iiMaleSelectionButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int iiTabBox = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int iiTextBox = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int image = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int index = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int instagram = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Joinning = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int leaves = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int LeftTopCorner = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int MaritalStatus = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int name = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int NotePad = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int NotePad128 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Notes = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notify = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Notify128 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int password = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int persons = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ProfileImage = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int refresh = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int RigthTopCorner = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int scott = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int SelectedButton = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int selectedFemale = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int selectedMale = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int slideout = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int summary = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Title = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ToDate = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int twitter = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int twitternav = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int UnselectedButton = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int UnselectedFemale = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int UnselectedMale = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Usrename = 2130837563;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int calendar_grid = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int calendar_view = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int title = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int month = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] calendar_cell = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public const int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public const int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public const int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public const int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public const int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public const int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public const int calendar_cell_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
